# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jd',
            name='description',
            field=models.TextField(max_length=3000),
        ),
    ]
