# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_auto_20170801_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='jd',
            name='status',
            field=models.BooleanField(default='True'),
        ),
    ]
