# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 07:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_jd_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jd',
            old_name='status',
            new_name='isActive',
        ),
    ]
