# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_auto_20170801_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jd',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
